#!/usr/bin/env python

import sys
import itertools

word = " ".join(sys.argv[1:])
if not word:
	quit

letters = list(word.lower())
letters = ["%s%s" % (x.upper(), x) for x in letters]
for x in itertools.product(*letters): print("".join(x))