#!/usr/bin/env python

import sys
import curses

class ChatWindow:
	focus = ""

class TextArea:
	text = ""
	scroll_position = 0
	RIGHT = 1
	LEFT = -1
	
	def addchr(c):
		TextArea.text += c
		TextArea.checksize()
	
	def delchr(index):
		if index >= 0 and index < len(TextArea.text):
			TextArea.text = list(TextArea.text)
			TextArea.text.pop(index)
			TextArea.text = "".join(TextArea.text)
			TextArea.checksize()
	
	def checksize():
		pass

class Chat:
	def __init__(self, name):
		pass

def _handle_resize(stdscr):
	stdscr.clear()
	stdscr.refresh()
	size = stdscr.getmaxyx()
	sys.stderr.write("Now %u x %u\n" % (size[1],size[0]))
	stdscr.resize(size[0], size[1])
	return stdscr

def main(stdscr):
	while 1:
		input = stdscr.getch()
		if input == curses.KEY_RESIZE:
			_handle_resize(stdscr)
		elif input == ord("q"):
			sys.exit()

try:
	curses.wrapper(main)
except KeyboardInterrupt:
	quit()
