#!/bin/bash

BITBUCKET_USER="shaunmitchell"
BITBUCKET_TOKEN="${BITBUCKET_TOKEN:-$(pass show bitbucket/app-passwords/default)}"
ORGANIZATION="trinoor"
REPO="21-05-opg-as9"
CUST="${1}"
TARGET_BRANCH="${2:-release}"

[[ -z "${BITBUCKET_USER}" || -z "${BITBUCKET_TOKEN}" ]] \
    && echo "must provide username and token" \
    && exit 1

# Get the HEAD of the target branch
printf "Getting HEAD for '${TARGET_BRANCH}' ... "
target_head=$(
    curl -s "https://api.bitbucket.org/2.0/repositories/${ORGANIZATION}/${REPO}/refs/branches/${TARGET_BRANCH}" \
        -u "${BITBUCKET_USER}:${BITBUCKET_TOKEN}" \
            | python -m json.tool \
            | grep -Po '"hash": "\K[^"]+' \
            | awk 'NR==1 {print; exit}'
)
echo "${target_head}"

# Create the src branch off of the target branch
printf "Creating branch '${CUST}' ... "
resp=$(
    curl -s "https://api.bitbucket.org/2.0/repositories/${ORGANIZATION}/${REPO}/refs/branches" \
        -u "${BITBUCKET_USER}:${BITBUCKET_TOKEN}" \
        --header 'Content-Type: application/json' \
        --data \
        '{
            "name": "'"${CUST}"'",
            "target": {
                "hash": "'"${target_head}"'"
            }
        }'
)
[[ "${resp}" =~ "error" ]] \
    && echo "error, exiting" && exit 1 \
    || echo "done"

# Create the trigger file
printf "Creating trigger file for '${CUST}' ... "
resp=$(
    curl -s "https://api.bitbucket.org/2.0/repositories/${ORGANIZATION}/${REPO}/src" \
        -u "${BITBUCKET_USER}:${BITBUCKET_TOKEN}" \
        -F branch="${CUST}" \
        -F "/${CUST}=${CUST}" \
        -F files="${CUST}" \
        -F message="${CUST} created online with Bitbucket"
)
[[ "${resp}" =~ "error" ]] \
    && echo "error, exiting" && exit 1 \
    || echo "done"

# Create the PR to the destination branch
printf "Creating PR from '${CUST}' to '${TARGET_BRANCH}' ... "
resp=$(
    curl -s "https://api.bitbucket.org/2.0/repositories/${ORGANIZATION}/${REPO}/pullrequests" \
        -u "${BITBUCKET_USER}:${BITBUCKET_TOKEN}" \
        --request POST \
        --header 'Content-Type: application/json' \
        --data \
        '{
            "title": "Merged in '"${CUST}"'",
            "source": {
                "branch": {
                    "name": "'"${CUST}"'"
                }
            },
            "destination": {
                "branch": {
                    "name": "'"${TARGET_BRANCH}"'"
                }
            }
        }' \
            | python -m json.tool
)
pr_id=$(echo "${resp}" | grep -Po '"id": \K\d+' | awk 'NR==1 {print; exit}')
[[ -z "${pr_id}" ]] \
    && echo "${resp}" && echo "error, exiting" && exit 1 \
    || echo "${pr_id}"

# Merge the pull request
printf "Completing the pull request ... "
resp=$(
    curl -s "https://api.bitbucket.org/2.0/repositories/${ORGANIZATION}/${REPO}/pullrequests/${pr_id}/merge" \
        -u "${BITBUCKET_USER}:${BITBUCKET_TOKEN}" \
        --request POST \
        --header 'Content-Type: application/json' \
        --data \
        '{
            "close_source_branch": true,
            "merge_strategy": "merge_commit"
        }'
)
[[ "${resp}" =~ "error" ]] \
    && echo "error, exiting" && exit 1 \
    || echo "done"
