#!/usr/bin/env python

import sys

if '-r' in sys.argv:
	reverse = True
else:
	reverse = False

word = eval(input(":"))
if type(word) != bytes:
	word = str(word).encode()
offset = 0

while 1:
	neword = b''
	for x in word:
		try:
			neword = neword + chr(ord(x) + offset).encode()
		except:
			neword = neword + chr(x + offset).encode()
	print(offset, "=>", neword)
	if reverse:
		offset -= 1
	else:
		offset += 1
