CREATE OR REPLACE PACKAGE LIB_APP AS PROCEDURE TRACE
(
  i_trace_proc     IN LIB_TRACE.TRACE_PROC%TYPE
 ,i_trace_user     IN LIB_TRACE.TRACE_USER%TYPE
 ,i_trace_level    IN LIB_TRACE.TRACE_LEVEL%TYPE
 ,i_trace_text     IN LIB_TRACE.TRACE_TEXT%TYPE
);

END;
/