create or replace TRIGGER AS9.TASSECINS
AFTER INSERT
ON AS9.TIDSECUS
referencing new as new
FOR EACH ROW

declare

USER_ID_V       CHAR(64);
PROFILE_CNT     NUMBER;
FACILITY_CNT     NUMBER;
XREF_CNT        NUMBER;

begin

SELECT COUNT(*) INTO PROFILE_CNT FROM AS9.TIDCVVAL WHERE TRIM(CODE_QUAL_VAL) = 'PROFILE' AND TRIM(ELEM_NBR) = 'HLXSEC' AND CODE_VALUE = :NEW.SECURITY_PROFILE;
SELECT COUNT(*) INTO FACILITY_CNT FROM AS9.TIDCVVAL WHERE TRIM(CODE_QUAL_VAL) = 'FACILITY' AND TRIM(ELEM_NBR) = 'HLXSEC' AND CODE_VALUE = :NEW.FACILITY;

    IF PROFILE_CNT <> 0 AND FACILITY_CNT <> 0

    THEN

        SELECT NVL(COUNT(*), 0)
        INTO
        XREF_CNT
        FROM AS9.TIDURLDT PU
        WHERE TRIM(ALERT_TRANS_NUMBER) = TRIM(:NEW.PASSPORT)
        AND PU.URL_TYPE = 'LOGIN-XREF';

        IF XREF_CNT = 0 THEN

            USER_ID_V := TRIM(:NEW.PASSPORT);

        ELSE
            SELECT
                PU.URL_ADDRESS
                INTO
                USER_ID_V
                FROM AS9.TIDURLDT PU
                WHERE TRIM(PU.ALERT_TRANS_NUMBER) = TRIM(:NEW.PASSPORT)
                AND PU.URL_TYPE = 'LOGIN-XREF';
        END IF;

    INSERT INTO AS9.HELIX_SYNC
    (HELIX_SYNC_ID,
	SYNC_OBJECT_TYPE,
	SYNC_OBJECT_ID,
    SYNC_OBJECT_ID2,
    SYNC_OBJECT_ID3,
	SYNC_TRANS_DATE,
	SYNC_STATUS,
	CHANGE_USER,
	CHANGE_DATE)
    VALUES
    (AS9.HELIX_SYNCH_ID_SEQ.nextval,
    'SECURITY',
    TRIM(USER_ID_V),
    'INSERT/UPDATE',
    TRIM(:NEW.FACILITY)||'-'||:NEW.SECURITY_PROFILE,
    SYSDATE,
    'N',
    'TASSEC',
    SYSDATE);

    END IF;

END;
