#!/usr/bin/env python

import os
import sys
import time
import random
import readline

length = 0

sleeptime = float(input('Enter sleep time: '))

while 1:
	answer = random.randrange(10**length, 10**(length+1))

	print("%d " % answer, end="")
	sys.stdout.flush()
	time.sleep(sleeptime)
	print('\r' + ' '*len(str(answer)) + '\r', end="")
	
	try:
		guess = int(input(': '))
	except:
		print('dumbfuck')
		quit()
	
	if guess != answer:
		print('[fail] %d' % answer)
		break
	else:
		length += 1
		word = "success"
		wordlen = len(word)
		while word.strip():
			print("\r" + word, end="")
			time.sleep(.4)
			word = word[:-1]
			print("\r" + " "*wordlen, end="\r")
