#!/usr/bin/env python

import os
import sys
import time
import string
import random

length = 0

sleeptime = float(input('Enter sleep time: '))

while 1:
	answer = random.randrange(10**length, 10**(length+1))
	atuple = tuple(str(answer))
	btuple = list(string.ascii_uppercase[:len(str(answer))])
	adict = {}
	for x in range(0, len(atuple)):
		adict[btuple[x]] = atuple[x]
	
	print(*atuple, sep=" ", end=" ")
	sys.stdout.flush()
	time.sleep(sleeptime)
	print('\r', end="")
	print(*btuple, sep=" ")
	
	# now loop through a-X of the btuple randomly
	while btuple:
		r = random.randrange(0, len(btuple))
		letter = btuple.pop(r)

		guess = input(letter + ": ")
		if guess != adict[letter]:
			print('[fail] ' + " ".join(atuple))
			quit()
	length += 1
	print()
